---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudflare-ddns-fbs-configmap
    files:
      - ./scripts/cloudflare-ddns.sh
generatorOptions:
  disableNameSuffixHash: true
