apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZSIcglkY9wIsC+WPbpyLvhAWUpeb1FZKgdVpwSFjaJwFyk5i,iv:sC8RpaKfuNMpvd1IZeL5mAXfmi24IsqnkOMN/b6ifSc=,tag:2hCf7sdhRej+2NyJukQd1g==,type:str]
    credentials.json: ENC[AES256_GCM,data:KkaBLvwd/CyySCr+rG9ThCgNJ8vRbG3zroqJXm51916nYo6FEa0EXVlBY5usjFx8itUqQI72dlFtbTpDNVq6RwNViRaYIDVs8m4tUa+n6WILZqPe3MUSx7NeBHa4Kd+dYPjI6wJrVsOS9Ejo6FeknAULIfaMXN2loGrblnuM6Pp6PC99hZK2qDE4DjGB3Z9lwQvksGFjDa1SQ0MV9XQuQOzCVhy1MHOTTaAjAbh1dw==,iv:ZPbk9wTK2nynSZ6+comrgvCxh2/LROug2ABd4LVB1Xc=,tag:zokFfN/jVhn9YA2//y1WPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONjhDZmJHaGZCUTViOUZh
            OWdwUVJmVmxFR2ZoNGN2TTZlRW9zWjNDK2xzCkpyU3c4bGVNWnE5MWNuVm81N2VC
            cGRYQ3BPYytGRUtyRlltTXUwWVZiQ2MKLS0tIEFOMGxRSnNXOGNIZWFjR0xIcW1V
            YmYzd3ZqTnhjODBydmdNSlJvZXliODgKddH9ONhmpwKH1C05aDcs02MVrJJoSi+A
            tw6oxRc/cl4CZ60VgZTCU/TROnx8QDIoBdxDBZi3QVFXaTdQuJxBBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T01:21:26Z"
    mac: ENC[AES256_GCM,data:C/5IsxaIX8/zXfsFaMYXL0W2I0VurALjOadlTWvMjwovIq/cYloWiAlOIbTv4raoGfqIdSEwwtjseYYJvom3NwX1Dz+iZ47M2jCbzQGnAKZ0HnwO4HReSuGBDmGy4AgB4E+v2z1zFvg0MmFtkG8ahhP7cQ/nvEHrkAqtCzDI1XY=,iv:a796Iy9DDhQGojlo1iJLqcqfMNQh2mc4H2lyc9O0eoE=,tag:a7xSiaAh4tZQPJ7WRpDUJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
