---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app fbs-nginx
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/network/fbs-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: fuzzlab-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
