---
kubernetes:
  children:
    controllers:
      hosts:
        "k3s201":
          ansible_user: "rancher"
          ansible_host: "10.0.2.201"
    workers:
      hosts:
        "k3s202":
          ansible_user: "rancher"
          ansible_host: "10.0.2.202"
        "k3s203":
          ansible_user: "rancher"
          ansible_host: "10.0.2.203"
        "k3s204":
          ansible_user: "rancher"
          ansible_host: "10.0.2.204"
        "k3s205":
          ansible_user: "rancher"
          ansible_host: "10.0.2.205"
        "k3s206":
          ansible_user: "rancher"
          ansible_host: "10.0.2.206"
