apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:vaVd2GztlBl0E6Ja42AjiJKuuwo5DgL6M78wbA4QGwxxO96nghQg8w==,iv:lagUXNv0+ocB+efAlMjmn903W5Z3EAlr6PbHePgpepg=,tag:QUcNgMGkt1tRNYOEjXkkDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZlRvYVZDZzBncTZSTHFs
            WmFER0F6WUptak1hMGgvczZhWkhpQWhEVkFJClkzbWowUFdvQ08vN29JZ0tDa1k4
            WVRGRld6clRXeDZDUGlraVhOYmU3S2cKLS0tIHZUZG1wV2VpNHorU2tqejJSN2VF
            MXJheTNwUFlEbHptN3paVVFpZ2xlOEEKRvSoyEsGZAXuXH/JFAtMJpn2XO4UOJOx
            gj4FsLurIYwRy4Iu/XDZhlnM4jBlQX3xoCT7BG5T2AEa1c98uHJB7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T23:50:59Z"
    mac: ENC[AES256_GCM,data:wI8ZJvanySgmRSeTk9VKtbjYuwrETPMdkGZvdEyfpDvli83qDyt1A5bv+qc5BHXBQgxddU/Px3tO3Xg9yjHfj+8oxnS6pvqLnE27Np0gNddZffas0FPwy3Rz/7ZYViWYNF2RgrmGQ2wIUpvRWN/Uj9SagCW9Iq4VSDEslk3C5sE=,iv:xGlMhLZHzdWSWDJlbu7yyZVOnCxH439niNculjgD31Y=,tag:vRIY5UiRTDIyZZJmrfEYiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
