apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:XAgaPRjwd2Bj64PeGc2xC+u01neqKCNYAed/cZcyBIAIJMqolPOl6A==,iv:93ziHs1c4l21ve23nXBBebCvMFIP3vTDlokRyzt2jCw=,tag:I/vkUHngTRvBwhbmjOIyBQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU0EwcGJJekdsdzBkOHpV
            YXhJQTVHV0VLN0pseVJreTB6MGNpdFBrQ1VVCmhMTG5DUDJ5dEw5UlYrbW0rZHU4
            OXhyWjlUUEkwQkNJRU1yekduWUFnNWcKLS0tIEJOaXd4dnl0TnVnVWppVitONk5C
            T3Nhd2ZGcTJjdTlJNTRzS040MFVHSWcKHg0Abw+3jn0XZXnN8rQ2CL80Yd0hSd/G
            PB6Rq0SimZsKgkUip7iCQp8bDYJSlUM4sHQW+QsYas/VmeuL/xEFBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T01:21:26Z"
    mac: ENC[AES256_GCM,data:/9yT+XfzwqA/d98OuHNOtahD2vYWRJww0or5G0HLJQwCCNssJQNrcTK7ecdBjbtg2wME5rlNPYEKOSndU5U3JEopzItOO3CvMzfuwykELVj6iRQdg458XGlD3nr5hUZbDKmFd3j5Qf1YnUbfIK0QrLKGv3sN8KmyAiln8xlHCE8=,iv:66luTUkJgCKDeA67okr9P9RhEMDCtWNPMeZ0EKES+9k=,tag:Px0P9K6Pz97n/lyk2+4jcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
