---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
spec:
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_FBE/./-}-production"
spec:
  secretName: "${SECRET_DOMAIN_FBE/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_FBE}"
  dnsNames:
    - "${SECRET_DOMAIN_FBE}"
    - "*.${SECRET_DOMAIN_FBE}"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_SEPF/./-}-production"
spec:
  secretName: "${SECRET_DOMAIN_SEPF/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_SEPF}"
  dnsNames:
    - "${SECRET_DOMAIN_SEPF}"
    - "*.${SECRET_DOMAIN_SEPF}"
