apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:gPqkIPYOqrvujCcLP62MmRRa6v6lHgkfMoVm1OvEXDPA4VTchR3oRktgGZeKLteLKvwIuE63IEOrhImMcOLbdqDTV8zP44U7WBgRdgXnJ8jaYxkvMfJSgp6+ruVf9Q==,iv:QVG35IzAuUyeu0DCTOM1CR0cNCdqGcOaHTwkTwmkyRY=,tag:Y3DUrWvW5vKz1DiQ39mTSw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dEwJ1YusKZg=,iv:1EkQlwKAKvFozgTr9/8FujoA5LqJvGanlH/kKrBFLtA=,tag:4SoupwzpCK5k/6LzOlLhnw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:pelvSGtQLrqR0oizJ41rPPBK,iv:Lijo79CakivBAV05eW3tLvKMJZxjIErUuVhGm7Q0OxQ=,tag:CQThA2mV0H3D6cHbZf+Dsw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:NkVYPqmrj0GJCBkQA52yjdIkQu+QSL+OR9slTehZHW5JGtLX,iv:ykdvYUVIr5ByKeOmLIJqrE7eVPEk8BB7adiiMkqO1ME=,tag:K3qXCx5pzVXSEKqVoRJmwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MFpQSEp1aWtNTXA0RDRT
            YnNOeCswemdJQ2ZwRS8yQm1yZUNQaS9hNENrCjZ4aHNLS09yeXF6Ym5OUUhtaGtX
            bHgxaGh4Yk9aT0M3L3pvbEFMOGZBajgKLS0tIDk3UkJ4a003ZXdwdldoYXFrdGEr
            QlpLWG1FczAwQkZaR2RqTTE3TUJ2NUEKgynfrOp9C8SA/IiyzaRanaprjm9Ff4OY
            TIbzdTLL8Lqu1YCVso5OoyA4SwY5gtl9WM7UNI+e4erJQPZEoZmmJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-07T01:21:26Z"
    mac: ENC[AES256_GCM,data:RHEbsJxJ1O72EZJ9WrgHghuNo2B1ItCRRrcNh60H42yZeQH4SYOuZczlRjC6ehkLm5MijhFCThChBbm8gSVBmV3w6zDxoVcbd6Mb1b4Tcz6wtwblUVrZqwJVZx67aGUotqDra+zslOFmzW7I4uOsSHvfiVN6+X/SjnPNNUySDTs=,iv:QBne92JB3uvUtVigcH/C2s8A9yczAUkdh/HJ/hulJ04=,tag:hj77R2oIoWM8ry6/cDHyNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
