---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.0.1.0/22"
  JELLYFIN_ADDR: "10.0.2.65"
  FIREFLY_ADDR: "10.0.2.68"
  PLEX_ADDR: "10.0.2.66"
  BUDGET_ADDR: "10.0.2.67"
  AUTH_ADDR: "10.0.2.64"
