---
apiVersion: v1
kind: Service
metadata:
  name: sepf
  namespace: default
spec:
  type: ExternalName
  externalName: ${DOCKGE_ADDR}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/upstream-vhost: ${DOCKGE_ADDR}
    external-dns-sepf.alpha.kubernetes.io/target: "${SECRET_DOMAIN_SEPF}"
  name: proxy-sepf
  namespace: default
spec:
  ingressClassName: sepf
  rules:
    - host: &host ${SECRET_DOMAIN_SEPF}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sepf
                port:
                  number: 880
  tls:
    - hosts:
        - *host
