---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app fbs-nginx
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2

  install:
    remediation:
      retries: 0

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 0

  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: false
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups: [160, 140, 241, 0, 10, 121]

    controllers:
      fbs-nginx:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/nginxinc/nginx-unprivileged
              tag: "1.27.1"
              pullPolicy: Always
            ports:
              - containerPort: 8080

    service:
      app:
        controller: fbs-nginx
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN_FBS}"
        hosts:
          - host: "*.${SECRET_DOMAIN_FBS}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
          - host: "${SECRET_DOMAIN_FBS}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: configMap
        name: nginx-configmap # overriden by kustomizeconfig
        globalMounts:
          - path: /config/nginx/nginx.conf
            subPath: config.yml
            readOnly: true

      config-dir:
        enabled: true
        existingClaim: fbs-nginx-config
        globalMounts:
          - path: /etc/nginx/conf.d
            readOnly: true

      files:
        enabled: true
        existingClaim: fbs-nginx-files
        globalMounts:
          - path: /var/www
            readOnly: true

      logs:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - subPath: "tmp"
            path: "/var/log/nginx/"

      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        globalMounts:
          - subPath: "tmp"
            path: "/var/cache/nginx"
