---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./pv-ceph.yaml

configMapGenerator:
  - name: nginx-configmap
    files:
      - ./config/config.yml

generatorOptions:
  disableNameSuffixHash: true
