---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fbs-nginx-files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: csi-cephfs-sc
  volumeName: fbs-nginx-files-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fbs-nginx-files-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: fbs-nginx-files
    namespace: network
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-network/fbs-nginx/files
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: fbs-nginx-f

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fbs-nginx-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-cephfs-sc
  volumeName: fbs-nginx-config-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fbs-nginx-config-pv
spec:
  storageClassName: csi-cephfs-sc
  claimRef:
    name: fbs-nginx-config
    namespace: network
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: cephfs.csi.ceph.com
    nodeStageSecretRef:
      # node stage secret name
      name: csi-cephfs-secret
      # node stage secret namespace where above secret is created
      namespace: storage
    volumeAttributes:
      # Required options from storageclass parameters need to be added in volumeAttributes
      "clusterID": "ace7b6a4-115a-42f7-ba4f-32ceeb11e3c3"
      "fsName": "k8s-cephfs"
      "staticVolume": "true"
      "rootPath": /volumes/csi/k8s-network/fbs-nginx/config
    # volumeHandle can be anything, need not to be same
    # as PV name or volume name. keeping same for brevity
    volumeHandle: fbs-nginx-c
