apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:exa08Ptihmk3ZEAsZM6wDqCFq8/skKFj,iv:5MhlLmhfQfGRyACWLOphgoMGe7Idptz09d1cyg+amHU=,tag:D1EGp6/z8V+qR3nSfgYgvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUFE5b2JwVzRtWk13MTE5
            ZnRjalZvVVY5cmt1SitYZ1dhWUFuSlpLblVvCndMdEFXVEdTYlRJNC93MmwxdDN2
            T3dHQnNyU29XODBPblFrSk5ESEo0ZlkKLS0tIDY2SlFIL0JiU0RVNXhoWmRaa1BC
            cDJEb0thb1NpSTNZQnZJeDZOWUozOUkKXGnaVyyJ+baWEe746eG7Dyos9a3yj2YH
            qrv+ZivWXNztr+GYjKyk/diJtWpr9ho1/1VsRKrGDqaUdOno71ma2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-06T20:23:41Z"
    mac: ENC[AES256_GCM,data:9XAYuVdCy0f1WIjAh9sZ3mgssts/ryZIejsqDp5YGsl9hTnmXnN3OZ4oe+22epNJW/lnDiQujQwU7E3eRpGCR8fAH3+d43Cvk0gjyT7rdVWoUpD1XwgnWduH4bx8AIBXKLiXLwkllYvmjXAXDw+pSmg4ofpSsJ2wt0KH5trIXes=,iv:uPNG/oftdCmESHnM8uh1hrNLMGerCD8LDLDzcxEBg4I=,tag:3xLV2s1FGptoaXI7viaUeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
