---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudflare-ddns
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      cloudflare-ddns:
        type: cronjob
        cronjob:
          schedule: "@hourly"
          successfulJobsHistory: 0
        containers: &container
          app:
            image:
              repository: ghcr.io/onedr0p/kubanetics
              tag: 2024.3.6@sha256:6556e8c4b0b732bd4eec99d8b1c44caafb0f2f653d827667f2684c24ec4af244
            command: ["/app/cloudflare-ddns.sh"]
            resources:
              requests:
                cpu: 5m
              limits:
                memory: 16Mi
    persistence:
      config:
        type: secret
        name: cloudflare-ddns-secret
        defaultMode: 0775
        globalMounts:
          - path: /app/cloudflare-ddns.sh
            subPath: cloudflare-ddns.sh
            readOnly: true
