---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config/adguard.yaml
  - ./config/ansible.yaml
  - ./config/cloud.yaml
  - ./config/dockge.yaml
  - ./config/frigate.yaml
  - ./config/powerwall.yaml
  - ./config/pve.yaml
