apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:iDgFoTWvrgdRK/WeeTaUSZ5jkq/rPZWbHSe451I23gNRBXw+6g7v2A==,iv:EUbOAklHrTWzq4t3SS1d5UXMjWn0pW5SnG9BgCs+hVQ=,tag:qwZID0TvFVv8RLHTkrzoYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e8t93m32pkq6v5pgce4gm39xmtm967j9scmnvnrwpkaccwvunsyspwz3kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd2lKVGZOMVBLeUNMUnIy
            Mk1jTnJVT2sxbklIVVFzOUF1WVFLZkNyNWhnCnNvalFReC9DSGRlYWNLV3BZcDBr
            NGhqcWczR1B3endDTk9OK1Y2aDQ2NTQKLS0tIFFvaWRqTFZxdTNVaTVsUXdNSFJu
            ditwUkxRNFV3alBNQjVuRnhLZWlLNWsKi+THdTKwaTFnzor6cU84Bs/v0NiBkHhi
            rbdq2pPoY9NrYSJhEBzqZd4v+mSP2aC9Sj6IAxabOAdEpD3BcXZVCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-06T21:22:08Z"
    mac: ENC[AES256_GCM,data:C2TvEY+uizAkcEgNvJo0FRbghbjrwfg+6NZRGQLsHH7FtPdRy5gsOecZm3RXRKW9EZd+d3yyLF6T464RGki1BCdIravJcDMAGqTPlnnbQ3exfNO1yTc3IFCkJULMsgIKopnip1CuVsJrTw29EYxWBFxrhtyrknjQb8zyw697V58=,iv:CaVPJJAhhr3n6HYnBUPQrcmVu0p9LpVb47Fw7zzhdTA=,tag:lOGGfKXqVZ0SVu1/0yfu3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
